export interface GetCurrentStocks {
  nmId: number;
  supplierArticle: string;
  barcode: number;
  orders: number;
  orderLastMonth: number;
  imageUrl: string | null;
  inWayToClient: number;
  sku: string;
  inWayFromClient: number;
  quantityFull: number;
  ordersSum: number;
  inAcceptance: number;
  salesSpeed: number;
  planTime: number;
  assemblyPeriod: number;
  deliveryTime: number;
  shipmentTime: number;
  reserve: number;
  reserveInPercent: number;
  cost: number;
  growthPercent: number;
  salePrice: number;
  supplier: string | null;
  middlePrice: number;
  itemId: number;
  color: string;
  classification: string;
  multiplicity: string;
  boxNumber: string;
  supplierOldArticle: string;
  category: string;
  wbCreatedAt: string | Date;
  title: string;
}
