name: Deploy to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 3425 -H 45.139.78.245 >> ~/.ssh/known_hosts

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -p 3425" ./ root@45.139.78.245:/opt/kama
